### ISSUE TITLE
whar

### ISSUE THREAD

**Issue by kitty14956590** [diyhrt/diyhrt.github.io#8]
**Describe the Issue**
404 page formatting issue when request contains more than one path segment

**Screenshots**
normal behavior: 
![image](https://user-images.githubusercontent.com/74184683/185723853-37db7997-109b-41b4-8b83-f882ad2d8f69.png)

unexpected behavior:
![image](https://user-images.githubusercontent.com/74184683/185723881-98bb76e7-3b04-4136-bbc3-c7bdf6506044.png)

**Please provide the following information:**
 - Device type [ Linux 5.15.0-47-generic ]
 - Browser [ Mozilla Firefox 103.0.2 ]

**Additional context**
expected behavior:
https://diyhrt.wiki/404
unexpected behavior:
https://diyhrt.wiki/path/404

I forgor 💀

**Comment by KwiiHours** [comment]
Thanks for letting us know! Should be fixed now.
